version: 0.0
os: linux
files:
  - source: /
    destination : /var
hooks:
  BeforeInstall:
  - location: scripts/install.sh
    runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root