version: 0.0
os: linux
files:
  - source: /
    destination : /home
hooks:
  AfterInstall:
  - location: scripts/install.sh
    runas: root
  ApplicationStart:
    - location: /home/scripts/start.sh
      runas: root