version: 0.0
os: linux
files:
  - source: /
    destination : /home
hooks:
  AfterInstall:
  - location: scripts/install.sh
    runas: root
    timeout: 60
  ApplicationStart:
  - location: scripts/start.sh
    runas: root